// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.Data
{
    using System;
    
    public enum ColumnGroupInterval
    {
        Default,
        Value,
        Date,
        DateMonth,
        DateQuarter,
        DateYear,
        DateRange,
        Alphabetical,
        DisplayText
    }
}
