// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using System;
    using System.Runtime.CompilerServices;
    
    public class DisplayTextRowData : TransformedRowData
    {
        public DisplayTextRowData(string displayFormat)
        {
            this.DisplayFormat = displayFormat;
        }
        
        protected override object TransformValue(object value) => 
            DisplayTextHelper.Instance.GetDisplayText(this.DisplayFormat, value);
        
        public string DisplayFormat { get; set; }
    }
}
