// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using System;
    
    public interface ICustomCellTextProvider
    {
        string Customize(object value, string formattedText, int rowHandle, string fieldName);
        
        bool CanCustomize { get; }
    }
}
