// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.Data;
    using DevExpress.XamarinForms.DataGrid;
    using System;
    
    public interface IFieldValueVisitor
    {
        object GetFieldValue(IRowData rowData);
        object GetFormattedFieldValue(IRowData rowData);
        
        Type FieldValueType { get; }
        
        ColumnSortMode ActualSortMode { get; }
    }
}
