// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid;
    using System;
    
    public interface IGridDataProvider
    {
        string GetCellDisplayText(string fieldName, int visibleIndex);
        object GetCellValue(string fieldName, int visibleIndex);
        Type GetColumnType(string fieldName);
        string GetDisplayText(object value, string fieldName, int visibleIndex);
        GroupRowData GetGroupRowData(int visibleIndex);
        string[] GetTotalSummary(int columnVisibleIndex);
        bool IsGroupRow(int visibleIndex);
        void SetCellValue(string fieldName, int visibleIndex, object value);
        
        int VisibleRowCount { get; }
    }
}
