// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using System;
    
    public interface IGridDataSourceSupportSortCache
    {
        void BeginSort();
        void EndSort();
        void PopulateColumnValues<T>(int[] rowHandles, string fieldName, T[] values, IFieldValueVisitor fieldValueVisitor);
    }
}
