// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using System;
    using System.Runtime.CompilerServices;
    using Xamarin.Forms;
    
    public static class PlatformHelper
    {
        static PlatformHelper()
        {
            try
            {
                string str = Device.RuntimePlatform;
                Platform = (str == "Android") ? Platforms.Android : ((str == "iOS") ? Platforms.iOS : ((str == "WPF") ? Platforms.WinPhone : ((str == "UWP") ? Platforms.UWP : Platforms.Other)));
            }
            catch
            {
                Platform = Platforms.Other;
            }
        }
        
        public static T OnPlatform<T>(T iOS, T Android, T WinPhone, T UWP)
        {
            switch (Platform)
            {
                case Platforms.iOS:
                    return iOS;
                
                case Platforms.Android:
                    return Android;
                
                case Platforms.WinPhone:
                    return WinPhone;
                
                case Platforms.UWP:
                    return UWP;
            }
            return default(T);
        }
        
        public static Platforms Platform { get; internal set; }
        
        public enum Platforms
        {
            iOS,
            Android,
            WinPhone,
            UWP,
            Other
        }
    }
}
