// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid;
    using System;
    
    public class SummaryCalculatorCount : SummaryCalculator
    {
        private long summaryValue;
        
        public override void AccumulateValue(IRowData row, object value, IToDecimalConverter converter)
        {
            if (value != null)
            {
                this.summaryValue += (long) value;
            }
        }
        
        public override bool Begin()
        {
            this.summaryValue = 0L;
            return true;
        }
        
        public override object End() => 
            ((long) this.summaryValue);
        
        public override object GetFinalResult() => 
            ((long) this.summaryValue);
        
        public override void ProcessValue(IRowData row, object value, IToDecimalConverter converter)
        {
            if (value != null)
            {
                this.summaryValue += 1L;
            }
        }
    }
}
