// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid;
    using System;
    
    public class SummaryCalculatorAverage : SummaryCalculator
    {
        private decimal count;
        private decimal summaryValue;
        
        public override void AccumulateValue(IRowData row, object value, IToDecimalConverter converter)
        {
            Tuple<decimal, decimal> tuple = value as Tuple<decimal, decimal>;
            if (tuple != null)
            {
                this.summaryValue = (decimal) (this.summaryValue + tuple.Item1);
                this.count = (decimal) (this.count + tuple.Item2);
            }
        }
        
        public override bool Begin()
        {
            this.summaryValue = 0M;
            this.count = 0M;
            return true;
        }
        
        public override object End() => 
            ((this.count > 0M) ? new Tuple<decimal, decimal>(this.summaryValue, this.count) : new Tuple<decimal, decimal>(0M, 0M));
        
        public override object GetFinalResult() => 
            ((this.count > 0M) ? ((object) ((decimal) (this.summaryValue / this.count))) : ((object) 0));
        
        public override void ProcessValue(IRowData row, object value, IToDecimalConverter converter)
        {
            this.count = (decimal) (this.count + 1);
            if (value != null)
            {
                this.summaryValue = (decimal) (this.summaryValue + converter.ToDecimal(value));
            }
        }
    }
}
