// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid;
    using System;
    using System.Runtime.CompilerServices;
    
    public abstract class TransformedRowData : IRowData
    {
        protected TransformedRowData()
        {
        }
        
        public object GetFieldValue(string fieldName)
        {
            object fieldValue = this.RowData.GetFieldValue(fieldName);
            return this.TransformValue(fieldValue);
        }
        
        public T GetFieldValueGeneric<T>(string fieldName)
        {
            T fieldValueGeneric = this.RowData.GetFieldValueGeneric<T>(fieldName);
            return (T) this.TransformValue(fieldValueGeneric);
        }
        
        public virtual object GetGroupValue(object transformedValue) => 
            transformedValue;
        
        protected abstract object TransformValue(object value);
        
        public IRowData RowData { get; set; }
        
        public int RowHandle
        {
            get => 
                this.RowData.RowHandle;
            set => 
                this.RowData.RowHandle = value;
        }
        
        public object DataObject =>
            this.RowData.DataObject;
    }
}
