// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Themes
{
    using System;
    using System.CodeDom.Compiler;
    using Xamarin.Forms;
    using Xamarin.Forms.Xaml;
    
    [XamlFilePath("Themes/DarkTheme.xaml")]
    public class DarkTheme : ResourceDictionary
    {
        public DarkTheme()
        {
            this.InitializeComponent();
        }
        
        [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "0.0.0.0")]
        private void InitializeComponent()
        {
            Extensions.LoadFromXaml<DarkTheme>(this, typeof(DarkTheme));
        }
    }
}
