// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using DevExpress.Data;
    using System;
    using System.Runtime.CompilerServices;
    
    public class DateColumn : TextColumn
    {
        public DateColumn()
        {
            this.IsNullable = false;
        }
        
        protected override ColumnGroupInterval CalculateActualColumnGroupInterval() => 
            ((base.GroupInterval != ColumnGroupInterval.Default) ? base.GroupInterval : ColumnGroupInterval.DateRange);
        
        protected override Type GetComparerPropertyType() => 
            base.GetComparerPropertyTypeCore();
        
        protected override string GetDefaultDisplayText() => 
            "{0:d}";
        
        public bool IsNullable { get; set; }
        
        protected override AutoFilterCondition DefaultAutoFilterCondition =>
            ((base.FilterMode == ColumnFilterMode.Value) ? AutoFilterCondition.Equals : AutoFilterCondition.Like);
    }
}
