// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using System;
    using System.Collections.Specialized;
    using System.ComponentModel;
    
    internal class EventArgsConverter
    {
        public static NotifyCollectionChangedEventArgs Convert(ListChangedEventArgs e, IBindingList bindingList)
        {
            switch (e.ListChangedType)
            {
                case ListChangedType.Reset:
                    return new NotifyCollectionChangedEventArgs((NotifyCollectionChangedAction) NotifyCollectionChangedAction.Reset);
                
                case ListChangedType.ItemAdded:
                    return new NotifyCollectionChangedEventArgs((NotifyCollectionChangedAction) NotifyCollectionChangedAction.Add, bindingList[e.NewIndex], e.NewIndex);
                
                case ListChangedType.ItemDeleted:
                    return new NotifyCollectionChangedEventArgs((NotifyCollectionChangedAction) NotifyCollectionChangedAction.Remove, new object(), e.OldIndex);
                
                case ListChangedType.ItemMoved:
                    return new NotifyCollectionChangedEventArgs((NotifyCollectionChangedAction) NotifyCollectionChangedAction.Move, bindingList[e.NewIndex], e.NewIndex, e.OldIndex);
            }
            return new NotifyCollectionChangedEventArgs((NotifyCollectionChangedAction) NotifyCollectionChangedAction.Replace, bindingList[e.NewIndex], null, e.OldIndex);
        }
    }
}
