// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using System;
    using System.Collections.Specialized;
    using System.Runtime.CompilerServices;
    
    public interface IGridDataSource
    {
        event NotifyCollectionChangedEventHandler GroupCollectionChanged;
        
        event NotifyCollectionChangedEventHandler RowCollectionChanged;
        
        int AddNewRow(IEditableRowData rowData);
        IEditableRowData CreateNewRow();
        int DeleteRow(int rowHandle);
        IGroupInfo GetGroup(int groupHandle);
        IRowData GetRow(int rowHandle, IRowData reuseRow);
        
        bool SupportsSorting { get; }
        
        bool SupportsGrouping { get; }
        
        bool SupportsFiltering { get; }
        
        int GroupCount { get; }
        
        int RowCount { get; }
        
        int SelectedRow { get; set; }
        
        Type ActualDataSourceType { get; }
    }
}
