// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using System.Collections.Generic;
    
    public interface IGridColumnsProvider
    {
        IList<GridColumn> GenerateColumns();
    }
}
