// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using System;
    
    public interface IRowData
    {
        object GetFieldValue(string fieldName);
        T GetFieldValueGeneric<T>(string fieldName);
        
        int RowHandle { get; set; }
        
        object DataObject { get; }
    }
}
