// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using DevExpress.XamarinForms.DataGrid.Internal;
    using System;
    
    internal interface ISortGroupDataSettings
    {
        PropertyAccessor GetPropertyAccessor(string name);
        
        SortDescriptor<IRowData> Comparer { get; set; }
        
        GroupDescriptor<IRowData> GroupBy { get; set; }
    }
}
