// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using System;
    using System.Runtime.CompilerServices;
    
    public class RowEditingEventArgs : SourceRowEventArgs
    {
        public RowEditingEventArgs(int rowHandle, int sourceRowIndex, EditingRowAction action) : base(rowHandle, sourceRowIndex)
        {
            this.Action = action;
        }
        
        public EditingRowAction Action { get; protected set; }
    }
}
