// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.Data;
    using System;
    using System.Collections.Generic;
    
    public class ComplexSortDescriptor<T> : SortDescriptor<T>, IComparer<T>
    {
        private readonly List<SortDescriptor<T>> descriptors;
        
        public ComplexSortDescriptor()
        {
            this.descriptors = new List<SortDescriptor<T>>();
        }
        
        public void Add(SortDescriptor<T> descriptor)
        {
            this.descriptors.Add(descriptor);
        }
        
        public override int Compare(T firstValue, T secondValue) => 
            base.Comparer.Compare(firstValue, secondValue);
        
        public override bool Equals(object obj)
        {
            ComplexSortDescriptor<T> descriptor = obj as ComplexSortDescriptor<T>;
            if (descriptor == null)
            {
                if (this.descriptors.Count != 1)
                {
                    return false;
                }
                SortDescriptor<T> descriptor2 = obj as SortDescriptor<T>;
                return ((descriptor2 != null) ? object.Equals(descriptor2, this.descriptors[0]) : false);
            }
            int num = this.descriptors.Count;
            if (descriptor.descriptors.Count != num)
            {
                return false;
            }
            for (int i = 0; i < num; i++)
            {
                if (!object.Equals(descriptor.descriptors[i], this.descriptors[i]))
                {
                    return false;
                }
            }
            return true;
        }
        
        public override int GetHashCode()
        {
            int num = this.descriptors.Count;
            int num2 = ~num;
            for (int i = 0; i < num; i++)
            {
                num2 ^= this.descriptors[i].GetHashCode();
            }
            return num2;
        }
        
        int IComparer<T>.Compare(T firstValue, T secondValue)
        {
            int num = this.descriptors.Count;
            if (num <= 0)
            {
                throw new InvalidOperationException();
            }
            for (int i = 0; i < num; i++)
            {
                int num3 = this.descriptors[i].Compare(firstValue, secondValue);
                if (num3 != 0)
                {
                    return num3;
                }
            }
            return 0;
        }
        
        public SortDescriptor<T> TryConvertToSingle() => 
            ((this.descriptors.Count > 0) ? ((this.descriptors.Count != 1) ? this : this.descriptors[0]) : null);
        
        public IReadOnlyList<SortDescriptor<T>> Descriptors =>
            ((IReadOnlyList<SortDescriptor<T>>) this.descriptors);
        
        public override IComparer<T> AscendingComparer
        {
            get => 
                this;
            set
            {
            }
        }
        
        public override bool IsSingleColumn =>
            (this.Descriptors.Count == 1);
        
        public override ColumnSortOrder SortOrder
        {
            get
            {
                int num = this.Descriptors.Count;
                return ((num > 0) ? ((num != 1) ? ColumnSortOrder.Ascending : this.Descriptors[0].SortOrder) : ColumnSortOrder.None);
            }
            set
            {
            }
        }
    }
}
