// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid;
    using System;
    using System.Data;
    using System.Runtime.CompilerServices;
    
    public class DataRowIRowData : IRowData, IEditableRowData
    {
        public object GetFieldValue(string fieldName)
        {
            object obj2 = this.DataRow[fieldName];
            return (!object.Equals(obj2, DBNull.Value) ? obj2 : null);
        }
        
        public T GetFieldValueGeneric<T>(string fieldName)
        {
            object obj2 = this.DataRow[fieldName];
            if (!object.Equals(obj2, DBNull.Value))
            {
                return (T) obj2;
            }
            return default(T);
        }
        
        public void SetFieldValue(string fieldName, object value)
        {
            if (value == null)
            {
                this.DataRow[fieldName] = DBNull.Value;
            }
            else
            {
                this.DataRow[fieldName] = value;
            }
        }
        
        public System.Data.DataRow DataRow { get; set; }
        
        public object DataObject =>
            this.DataRow;
        
        public int RowHandle { get; set; }
    }
}
