// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid.Localization;
    using System;
    
    public class DateYearRowData : TransformedRowData
    {
        public override object GetGroupValue(object transformedValue)
        {
            if (transformedValue == null)
            {
                return null;
            }
            DateTime time = (DateTime) transformedValue;
            return string.Format(GridLocalizer.GetString(GridStringId.GroupIntervalYearDisplayFormat), (int) time.Year);
        }
        
        protected override object TransformValue(object value)
        {
            if (value == null)
            {
                return null;
            }
            return new DateTime(((DateTime) value).Year, 1, 1);
        }
    }
}
