// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using System;
    
    public class DateRowData : TransformedRowData
    {
        protected override object TransformValue(object value)
        {
            if (value is DateTime)
            {
                return ((DateTime) value).Date;
            }
            return null;
        }
    }
}
