// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid.Localization;
    using System;
    using System.Globalization;
    
    public class DateMonthRowData : TransformedRowData
    {
        public override object GetGroupValue(object transformedValue)
        {
            if (transformedValue == null)
            {
                return null;
            }
            DateTime time = (DateTime) transformedValue;
            string str = CultureInfo.get_CurrentCulture().get_DateTimeFormat().get_MonthNames()[time.get_Month() - 1];
            return string.Format(GridLocalizer.GetString(GridStringId.GroupIntervalMonthDisplayFormat), str, (int) time.get_Year());
        }
        
        protected override object TransformValue(object value)
        {
            if (value == null)
            {
                return null;
            }
            DateTime time = (DateTime) value;
            return new DateTime(time.get_Year(), time.get_Month(), 1);
        }
    }
}
