// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid;
    using System;
    
    public abstract class GroupDescriptor<T> : SortDescriptor<T>
    {
        protected GroupDescriptor()
        {
        }
        
        public abstract object GetGroupValue(IRowData rowData);
    }
}
