// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid;
    using System;
    
    public interface IGridControlTest
    {
        void CellDoubleTap(int rowVisibleIndex, int columnIndex);
        void CellLongTap(int rowVisibleIndex, int columnIndex);
        void CellTap(int rowVisibleIndex, int columnIndex);
        void ChangeColumnSorting(string fieldName);
        CellStyle GetActualCellStyle();
        GroupRowStyle GetActualGroupRowStyle();
        HeaderStyle GetActualHeaderStyle();
        SwipeButtonStyle GetActualSwipeButtonStyle();
        TotalSummaryStyle GetActualTotalSummaryStyle();
        
        int GroupCount { get; }
        
        CellStyle CellStyleInternal { get; }
        
        GroupRowStyle GroupRowStyleInternal { get; }
        
        HeaderStyle HeaderStyleInternal { get; }
        
        TotalSummaryStyle TotalSummaryStyleInternal { get; }
        
        SwipeButtonStyle SwipeButtonStyleInternal { get; }
        
        bool IsLocked { get; }
        
        DevExpress.XamarinForms.DataGrid.EditRowViewModel EditRowViewModel { get; }
    }
}
