// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using System;
    
    public interface IReadWriteDataProcessingLocker
    {
        void BeginCancellableRead(ICancellableReader reader);
        void CancelReaders();
        void EndCancellableRead(ICancellableReader reader);
    }
}
