// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid;
    using System;
    
    public class ObjectRowData : IEditableRowData, IRowData
    {
        private object obj;
        private int rowHandle;
        private readonly PropertyAccessorCache cache;
        
        private ObjectRowData(object obj, int rowHandle, PropertyAccessorCache cache)
        {
            this.obj = obj;
            this.rowHandle = rowHandle;
            this.cache = cache;
        }
        
        public static ObjectRowData Create(object obj, int rowHandle, PropertyAccessorCache cache) => 
            new ObjectRowData(obj, rowHandle, cache);
        
        public object GetFieldValue(string fieldName) => 
            this.cache.GetAccessor(this.obj.GetType(), fieldName)?.GetValue(this.obj);
        
        public T GetFieldValueGeneric<T>(string fieldName)
        {
            PropertyAccessor accessor = this.cache.GetAccessor(this.obj.GetType(), fieldName);
            if (accessor != null)
            {
                return accessor.GetValueGeneric<T>(this.obj);
            }
            return default(T);
        }
        
        public void SetFieldValue(string fieldName, object value)
        {
            PropertyAccessor accessor = this.cache.GetAccessor(this.obj.GetType(), fieldName);
            if (accessor != null)
            {
                accessor.SetValue(this.obj, value);
            }
        }
        
        public int RowHandle
        {
            get => 
                this.rowHandle;
            set => 
                this.rowHandle = value;
        }
        
        public object DataObject
        {
            get => 
                this.obj;
            internal set => 
                this.obj = value;
        }
    }
}
