// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid;
    using System;
    
    public class SummaryCalculatorSum : SummaryCalculator
    {
        private decimal summaryValue;
        
        public override bool Begin()
        {
            this.summaryValue = 0M;
            return true;
        }
        
        public override object End() => 
            this.summaryValue;
        
        public override object GetFinalResult() => 
            this.summaryValue;
        
        public override void ProcessValue(IRowData row, object value, IToDecimalConverter converter)
        {
            if (value != null)
            {
                this.summaryValue = (decimal) (this.summaryValue + converter.ToDecimal(value));
            }
        }
    }
}
