// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid;
    using System;
    
    public abstract class SummaryCalculator
    {
        protected SummaryCalculator()
        {
        }
        
        public virtual void AccumulateValue(IRowData row, object value, IToDecimalConverter converter)
        {
            this.ProcessValue(row, value, converter);
        }
        
        public abstract bool Begin();
        public abstract object End();
        public abstract object GetFinalResult();
        public abstract void ProcessValue(IRowData row, object value, IToDecimalConverter converter);
    }
}
