// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using DevExpress.XamarinForms.DataGrid;
    using System;
    
    public class SummaryCalculatorNone : SummaryCalculator
    {
        public override bool Begin() => 
            false;
        
        public override object End() => 
            ((int) 0);
        
        public override object GetFinalResult() => 
            ((int) 0);
        
        public override void ProcessValue(IRowData row, object value, IToDecimalConverter converter)
        {
        }
    }
}
