// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid.Internal
{
    using System;
    
    public class ValueRowData : TransformedRowData
    {
        protected override object TransformValue(object value) => 
            value;
    }
}
