// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using System;
    using System.Runtime.CompilerServices;
    using System.Threading;
    using System.Windows.Input;
    
    internal class ApplyAutoFilterCommand : ICommand
    {
        private GridColumn column;
        [CompilerGenerated]
        public event EventHandler CanExecuteChanged;

        public ApplyAutoFilterCommand(GridColumn column)
        {
            this.column = column;
        }

        public bool CanExecute(object isComplete) => 
            (!this.column.AllowAutoFilter ? ((bool) false) : (this.column.ImmediateUpdateAutoFilter ? ((bool) true) : (this.column.ImmediateUpdateAutoFilter ? ((bool) false) : ((bool) ((bool) isComplete)))));
        
        public void Execute(object value)
        {
            this.column.AutoFilterValue = object.Equals(value, string.Empty) ? null : value;
        }
        
        private void RaiseCanExecuteChanged()
        {
            if (this.CanExecuteChanged != null)
            {
                this.CanExecuteChanged(this, new EventArgs());
            }
        }
    }
}
