// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using DevExpress.XamarinForms.DataGrid.Internal;
    using System;
    using System.Runtime.CompilerServices;
    
    public class CellData : NotificationObject
    {
        private object _value;
        private string _displayText;
        private bool _isSelected;
        private object _source;
        
        public object Value
        {
            get => 
                this._value;
            set
            {
                if (this._value != value)
                {
                    this._value = value;
                    base.OnPropertyChanged("Value");
                }
            }
        }
        
        public string DisplayText
        {
            get => 
                this._displayText;
            set
            {
                if (this._displayText != value)
                {
                    this._displayText = value;
                    base.OnPropertyChanged("DisplayText");
                }
            }
        }
        
        public bool IsSelected
        {
            get => 
                this._isSelected;
            internal set
            {
                if (this._isSelected != value)
                {
                    this._isSelected = value;
                    base.OnPropertyChanged("IsSelected");
                }
            }
        }
        
        public object Source
        {
            get => 
                this._source;
            set
            {
                if (this._source != value)
                {
                    this._source = value;
                    base.OnPropertyChanged("Source");
                }
            }
        }
        
        public CellIndex Index { get; set; }
    }
}
