// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using System;
    using System.CodeDom.Compiler;
    using System.Runtime.InteropServices;
    using Xamarin.Forms;
    using Xamarin.Forms.Xaml;
    
    [XamlFilePath("EditFormView/EditFormPage.xaml")]
    public class EditFormPage : ContentPage
    {
        private DataGridView dataGridView;
        private object item;
        private DataTemplate template;
        
        public EditFormPage(DataGridView dataGridView, object item, DataTemplate template = null)
        {
            this.InitializeComponent();
            this.dataGridView = dataGridView;
            this.item = item;
            this.template = template;
            base.set_Content(this.CreateContent());
        }
        
        private View CreateContent()
        {
            if (this.template == null)
            {
                EditFormView view1 = new EditFormView();
                view1.DataGridView = this.dataGridView;
                view1.Item = this.item;
                return view1;
            }
            int rowHandle = this.dataGridView.FindRowByDataObject(this.item);
            View view2 = (View) this.template.CreateContent();
            view2.set_BindingContext(this.dataGridView.GetEditRowViewModel(new CellIndex(rowHandle, string.Empty), false));
            return view2;
        }
        
        [GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "0.0.0.0")]
        private void InitializeComponent()
        {
            Extensions.LoadFromXaml<EditFormPage>(this, typeof(EditFormPage));
        }
        
        private void Save_Clicked(object sender, EventArgs e)
        {
            EditFormView view = base.get_Content() as EditFormView;
            if (view != null)
            {
                view.Commit();
            }
            else
            {
                EditRowViewModel editRowViewModel = (EditRowViewModel) base.get_Content().get_BindingContext();
                this.dataGridView.ApplyEditorResults(editRowViewModel);
            }
            base.get_Navigation().PopAsync();
        }
    }
}
