// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using DevExpress.Data.Filtering;
    using System;
    using System.Runtime.CompilerServices;
    
    internal class GridAutoFilter
    {
        public CriteriaOperator FilterExpression { get; set; }
        
        public GridColumn Column { get; set; }
    }
}
