// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using System;
    using System.Runtime.CompilerServices;
    
    public class GroupRowData
    {
        public GroupRowData(string value, string summary, bool isCollapsed)
        {
            this.Value = value;
            this.Summary = summary;
            this.IsCollapsed = isCollapsed;
        }
        
        public string Value { get; set; }
        
        public string Summary { get; set; }
        
        public bool IsCollapsed { get; set; }
    }
}
