// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using System;
    
    public interface IEditableRowData : IRowData
    {
        void SetFieldValue(string fieldName, object value);
    }
}
