// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using System;
    using System.Runtime.CompilerServices;
    
    public delegate void InternalCollectionChangedEventHandler(object sender, InternalCollectionChangedEventArgs e);
}
