// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using System;
    using Xamarin.Forms;
    
    public class NumberColumn : TextColumn
    {
        protected override Type GetComparerPropertyType() => 
            base.GetComparerPropertyTypeCore();
        
        protected override TextAlignment GetDefaultHorizontalContentAlignment() => 
            2;
    }
}
