// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using System;
    using System.Runtime.CompilerServices;
    
    public class SourceRowEventArgs : RowEventArgs
    {
        public SourceRowEventArgs(int rowHandle, int sourceRowIndex) : base(rowHandle)
        {
            this.SourceRowIndex = sourceRowIndex;
        }
        
        public int SourceRowIndex { get; protected set; }
    }
}
