// Generated by .NET Reflector from D:\workspace\mobile\hito-mobile\HitoApp\lampart_lib_dll\DevExpress.XamarinForms.Grid.dll
namespace DevExpress.XamarinForms.DataGrid
{
    using DevExpress.Data;
    using Xamarin.Forms;
    
    public class SwitchColumn : GridColumn
    {
        protected override TextAlignment GetDefaultHorizontalContentAlignment() => 
            TextAlignment.Center;
        
        protected override AutoFilterCondition DefaultAutoFilterCondition =>
            AutoFilterCondition.Equals;
    }
}
